import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { CreateTaskDto, UpdateTaskDto } from './dto/task.dto';
import { TaskPriority, TaskStatus } from '@prisma/client';

@Injectable()
export class TasksService {
  constructor(private prisma: PrismaService) {}

  async findAll(
    userId: string,
    filters: { status?: TaskStatus; priority?: TaskPriority; category?: string },
  ) {
    const where: any = { userId };

    if (filters.status) where.status = filters.status;
    if (filters.priority) where.priority = filters.priority;
    if (filters.category) where.category = filters.category;

    return this.prisma.task.findMany({
      where,
      orderBy: { createdAt: 'desc' },
    });
  }

  async create(userId: string, dto: CreateTaskDto) {
    return this.prisma.task.create({
      data: {
        userId,
        title: dto.title,
        description: dto.description,
        category: dto.category,
        priority: dto.priority ?? TaskPriority.MEDIUM,
        dueDate: dto.dueDate ? new Date(dto.dueDate) : undefined,
        linkedEntityType: dto.linkedEntityType,
        linkedEntityId: dto.linkedEntityId,
        isAutoGenerated: false,
      },
    });
  }

  async update(userId: string, id: string, dto: UpdateTaskDto) {
    const task = await this.prisma.task.findFirst({ where: { id, userId } });
    if (!task) throw new NotFoundException('Task not found');

    return this.prisma.task.update({
      where: { id },
      data: {
        ...(dto.title !== undefined && { title: dto.title }),
        ...(dto.description !== undefined && { description: dto.description }),
        ...(dto.status !== undefined && { status: dto.status }),
        ...(dto.priority !== undefined && { priority: dto.priority }),
        ...(dto.dueDate !== undefined && { dueDate: new Date(dto.dueDate) }),
        ...(dto.completedAt !== undefined && { completedAt: new Date(dto.completedAt) }),
      },
    });
  }

  async remove(userId: string, id: string) {
    const task = await this.prisma.task.findFirst({ where: { id, userId } });
    if (!task) throw new NotFoundException('Task not found');
    await this.prisma.task.delete({ where: { id } });
    return { success: true };
  }

  async generateSmartTasks(userId: string) {
    const profile = await this.prisma.profile.findUnique({ where: { userId } });
    if (!profile) return { created: [] };

    const created: string[] = [];

    // Check for LEGAL documents
    const legalDocCount = await this.prisma.document.count({
      where: { userId, category: 'LEGAL' },
    });

    const hasWillTask = await this.prisma.task.findFirst({
      where: { userId, title: 'Upload your Will document', isAutoGenerated: true },
    });

    if (legalDocCount === 0 && !hasWillTask) {
      await this.prisma.task.create({
        data: {
          userId,
          title: 'Upload your Will document',
          category: 'Legal',
          priority: TaskPriority.HIGH,
          isAutoGenerated: true,
        },
      });
      created.push('Upload your Will document');
    }

    // Check for EXECUTOR plan shares
    const executorShareCount = await this.prisma.planShare.count({
      where: { ownerId: userId, role: 'EXECUTOR' },
    });

    const hasExecutorTask = await this.prisma.task.findFirst({
      where: { userId, title: 'Assign an Executor', isAutoGenerated: true },
    });

    if (executorShareCount === 0 && !hasExecutorTask) {
      await this.prisma.task.create({
        data: {
          userId,
          title: 'Assign an Executor',
          category: 'Plan Sharing',
          priority: TaskPriority.HIGH,
          isAutoGenerated: true,
        },
      });
      created.push('Assign an Executor');
    }

    // Check if profile is incomplete
    const isIncomplete =
      !profile.firstName ||
      !profile.lastName ||
      !profile.dateOfBirth ||
      !profile.countryOfResidence;

    const hasProfileTask = await this.prisma.task.findFirst({
      where: { userId, title: 'Complete your profile', isAutoGenerated: true },
    });

    if (isIncomplete && !hasProfileTask) {
      await this.prisma.task.create({
        data: {
          userId,
          title: 'Complete your profile',
          category: 'Profile',
          priority: TaskPriority.MEDIUM,
          isAutoGenerated: true,
        },
      });
      created.push('Complete your profile');
    }

    return { created };
  }
}
