import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { TaskStatus } from '@prisma/client';

interface ChecklistStep {
  id: string;
  title: string;
  category: string;
}

const CHECKLIST_STEPS: ChecklistStep[] = [
  { id: '1', title: 'Notify immediate family', category: 'notification' },
  { id: '2', title: 'Contact the employer', category: 'administrative' },
  { id: '3', title: 'Get death certificates', category: 'legal' },
  { id: '4', title: 'Notify banks and financial institutions', category: 'financial' },
  { id: '5', title: 'Contact insurance companies', category: 'insurance' },
  { id: '6', title: 'Handle estate and will', category: 'legal' },
  { id: '7', title: 'Manage digital accounts', category: 'digital' },
  { id: '8', title: 'Settle final bills', category: 'financial' },
];

const GRIEF_RESOURCES = [
  {
    title: 'Understanding Grief',
    description: 'A guide to the stages of grief and how to cope with loss.',
    url: '',
  },
  {
    title: 'Estate Administration Basics',
    description: 'Step-by-step guidance on managing an estate after a loved one passes.',
    url: '',
  },
  {
    title: 'Notifying Government Agencies',
    description: 'How to notify social security, pension providers, and tax authorities.',
    url: '',
  },
  {
    title: 'Digital Legacy Management',
    description: 'Managing online accounts, social media, and digital assets after death.',
    url: '',
  },
  {
    title: 'Bereavement Support Services',
    description: 'Professional counselling and community support for those dealing with loss.',
    url: '',
  },
];

@Injectable()
export class PostLossService {
  constructor(private prisma: PrismaService) {}

  async getChecklist(userId: string) {
    const completedTasks = await this.prisma.task.findMany({
      where: {
        userId,
        status: TaskStatus.COMPLETED,
        category: { startsWith: 'POST_LOSS:' },
      },
    });

    const completedStepIds = new Set(
      completedTasks.map((t) => t.category?.replace('POST_LOSS:', '') ?? ''),
    );

    return CHECKLIST_STEPS.map((step) => ({
      ...step,
      completed: completedStepIds.has(step.id),
    }));
  }

  async completeStep(userId: string, stepId: string) {
    const category = `POST_LOSS:${stepId}`;
    const step = CHECKLIST_STEPS.find((s) => s.id === stepId);

    const existing = await this.prisma.task.findFirst({
      where: { userId, category },
    });

    if (existing) {
      return this.prisma.task.update({
        where: { id: existing.id },
        data: { status: TaskStatus.COMPLETED, completedAt: new Date() },
      });
    }

    return this.prisma.task.create({
      data: {
        userId,
        title: step?.title ?? `Post-loss step ${stepId}`,
        category,
        status: TaskStatus.COMPLETED,
        completedAt: new Date(),
        isAutoGenerated: true,
      },
    });
  }

  getResources() {
    return GRIEF_RESOURCES;
  }
}
