import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { CreateGoalDto, UpdateGoalDto } from './dto/goal.dto';

@Injectable()
export class GoalsService {
  constructor(private prisma: PrismaService) {}

  async findAll(userId: string, type?: string) {
    const tasks = await this.prisma.task.findMany({
      where: {
        userId,
        category: {
          startsWith: 'GOAL:',
          ...(type ? { equals: `GOAL:${type}` } : {}),
        },
        isAutoGenerated: false,
      },
      orderBy: { createdAt: 'desc' },
    });

    return tasks.map((t) => this.mapToGoal(t));
  }

  async create(userId: string, dto: CreateGoalDto) {
    const task = await this.prisma.task.create({
      data: {
        userId,
        title: dto.title,
        description: dto.description,
        category: `GOAL:${dto.type}`,
        dueDate: dto.deadline ? new Date(dto.deadline) : undefined,
        isAutoGenerated: false,
        // linkedEntityType = goal sub-category (e.g. "Health", "Finance")
        linkedEntityType: dto.category ?? null,
        // linkedEntityId = progressPct as string
        linkedEntityId: String(dto.progressPct ?? 0),
      },
    });

    return this.mapToGoal(task);
  }

  async update(userId: string, id: string, dto: UpdateGoalDto) {
    const existing = await this.prisma.task.findFirst({
      where: { id, userId, category: { startsWith: 'GOAL:' } },
    });
    if (!existing) throw new NotFoundException('Goal not found');

    const task = await this.prisma.task.update({
      where: { id },
      data: {
        title: dto.title ?? existing.title,
        description: dto.description ?? existing.description,
        category: dto.type ? `GOAL:${dto.type}` : existing.category,
        dueDate: dto.deadline ? new Date(dto.deadline) : existing.dueDate,
        linkedEntityType: dto.category ?? existing.linkedEntityType,
        linkedEntityId:
          dto.progressPct !== undefined
            ? String(dto.progressPct)
            : existing.linkedEntityId,
      },
    });

    return this.mapToGoal(task);
  }

  async remove(userId: string, id: string) {
    const existing = await this.prisma.task.findFirst({
      where: { id, userId, category: { startsWith: 'GOAL:' } },
    });
    if (!existing) throw new NotFoundException('Goal not found');

    await this.prisma.task.delete({ where: { id } });
    return { success: true };
  }

  private mapToGoal(task: {
    id: string;
    title: string;
    description: string | null;
    category: string | null;
    dueDate: Date | null;
    linkedEntityType: string | null;
    linkedEntityId: string | null;
    status: string;
    createdAt: Date;
    updatedAt: Date;
  }) {
    return {
      id: task.id,
      title: task.title,
      description: task.description,
      type: task.category?.replace('GOAL:', '') ?? null,
      deadline: task.dueDate,
      progressPct: task.linkedEntityId ? Number(task.linkedEntityId) : 0,
      category: task.linkedEntityType ?? null,
      status: task.status,
      createdAt: task.createdAt,
      updatedAt: task.updatedAt,
    };
  }
}
